// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: iMessage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The Message type containing all your requested fields
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`         // Unique ID (UUID)
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`       // The text content
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Additional message metadata if needed
	Client        string                 `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`   // Client identifier
	Lead          string                 `protobuf:"bytes,5,opt,name=lead,proto3" json:"lead,omitempty"`       // Lead/Contact identifier
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`   // Initial status (usually QUEUED)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_iMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_iMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_iMessage_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Message) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *Message) GetLead() string {
	if x != nil {
		return x.Lead
	}
	return ""
}

func (x *Message) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// The object pushed back to the caller
type StatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`       // Matching the message UID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // QUEUED, ACCEPTED, SENT, DELIVERED, RECEIVED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_iMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_iMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_iMessage_proto_rawDescGZIP(), []int{1}
}

func (x *StatusUpdate) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *StatusUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_iMessage_proto protoreflect.FileDescriptor

const file_iMessage_proto_rawDesc = "" +
	"\n" +
	"\x0eiMessage.proto\x12\bimessage\"\x8d\x01\n" +
	"\aMessage\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06client\x18\x04 \x01(\tR\x06client\x12\x12\n" +
	"\x04lead\x18\x05 \x01(\tR\x04lead\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"8\n" +
	"\fStatusUpdate\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2M\n" +
	"\x0eMessageService\x12;\n" +
	"\fSendAndTrack\x12\x11.imessage.Message\x1a\x16.imessage.StatusUpdate0\x01B\tZ\a./protob\x06proto3"

var (
	file_iMessage_proto_rawDescOnce sync.Once
	file_iMessage_proto_rawDescData []byte
)

func file_iMessage_proto_rawDescGZIP() []byte {
	file_iMessage_proto_rawDescOnce.Do(func() {
		file_iMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iMessage_proto_rawDesc), len(file_iMessage_proto_rawDesc)))
	})
	return file_iMessage_proto_rawDescData
}

var file_iMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_iMessage_proto_goTypes = []any{
	(*Message)(nil),      // 0: imessage.Message
	(*StatusUpdate)(nil), // 1: imessage.StatusUpdate
}
var file_iMessage_proto_depIdxs = []int32{
	0, // 0: imessage.MessageService.SendAndTrack:input_type -> imessage.Message
	1, // 1: imessage.MessageService.SendAndTrack:output_type -> imessage.StatusUpdate
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_iMessage_proto_init() }
func file_iMessage_proto_init() {
	if File_iMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iMessage_proto_rawDesc), len(file_iMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iMessage_proto_goTypes,
		DependencyIndexes: file_iMessage_proto_depIdxs,
		MessageInfos:      file_iMessage_proto_msgTypes,
	}.Build()
	File_iMessage_proto = out.File
	file_iMessage_proto_goTypes = nil
	file_iMessage_proto_depIdxs = nil
}
